### ISSUE TITLE
Make borders configurable

### ISSUE THREAD

**Issue by yngwi** [ziontee113/color-picker.nvim#10]
Hi
is it possible to make the borders configurable? I would like to use pointy corners instead of rounded ones.
Thank you!

**Comment by ziontee113** [comment]
It is possible. I'll implement it after I come back from my break.

**Comment by ziontee113** [comment]
Hi @yngwi , you can you change the border style. Please look at https://github.com/ziontee113/color-picker.nvim#set-things-up for example.

**Comment by yngwi** [comment]
Great, thank you!
