### ISSUE TITLE
Color picker doesn't recognize shorthand hex color

### ISSUE THREAD

**Issue by loc-cv** [ziontee113/color-picker.nvim#12]
First I want to thank you for this great plugin!

It seems like the picker doesn't auto-recognize shorthand hex color, for instance #777, which is shorthand for #777777.

My cursor is at #777, and when I use :PickColor, I expect the picker popup pre-populate the RGB for me.
![Screenshot from 2022-07-14 19-07-29](https://user-images.githubusercontent.com/89097473/178978788-8613dbb0-9f7e-46d5-8a8c-6626935f0020.png)

Actual behavior, all the RGB values are 0.
![Screenshot from 2022-07-14 19-07-39](https://user-images.githubusercontent.com/89097473/178979035-f339d0e2-0a8b-4fe2-9d55-87e9323b8531.png)

**Comment by ziontee113** [comment]
Yes, I haven't implemented that feature yet.
Will do in the short future :+1:

**Comment by ziontee113** [comment]
Yes, that is definitely a necessary feature to have. Unfortunately I can't tackle the issue for the time being. My apologies.
