### ISSUE TITLE
Change color of popup

### ISSUE THREAD

**Issue by lars-vc** [ziontee113/color-picker.nvim#14]
Not sure if this is a feature request or if I'm just missing it but, I would like to change the background color of the popup, currently it uses the color of my theme, but that blends in with the actual background too much. Is there a way to change this?
![image](https://user-images.githubusercontent.com/57136208/184091855-b249c331-4c03-4981-803e-e39be4cba22a.png)

**Comment by ziontee113** [comment]
Hi @lars-vc , you can now customize the popup's background & border colors using custom Highlight Groups.
Example Config:
```lua
require("color-picker").setup({
	["icons"] = { "ﱢ", "" },
	["border"] = "rounded", -- none | single | double | rounded | solid | shadow
	["keymap"] = { -- mapping example:
		["U"] = "<Plug>ColorPickerSlider5Decrease",
		["O"] = "<Plug>ColorPickerSlider5Increase",
	},
	["background_highlight_group"] = "your_custom_highlight_group",
	["border_highlight_group"] = "your_custom_highlight_group",
})
```

**Comment by lars-vc** [comment]
![image](https://user-images.githubusercontent.com/57136208/184122723-f42e134e-86b7-4397-a240-c4fd7c1bbf2f.png)
When I change the color it seems that spots with text still keep the original color.
![image](https://user-images.githubusercontent.com/57136208/184122497-54cc4697-f713-4f99-99b3-485c3a73919a.png)
![image](https://user-images.githubusercontent.com/57136208/184122537-3894ea7a-a165-4d75-aec9-8917d4b02dbc.png)
(Yellow was just to test)

**Comment by ziontee113** [comment]
Hmm... That's odd
![Screenshot from 2022-08-11 18-41-23](https://user-images.githubusercontent.com/102876811/184125714-4192e9e9-d46a-44f6-8418-4dba04541ec3.png)

I think you're mistaken the "foreground color" `guifg` with "background color" `guibg`. Maybe try changing your `guibg` to a different color.

**Comment by ziontee113** [comment]
The screenshot I sent you is using a different highlight group. In the screenshot you sent me I see you have `guibg=#1f292e` which is the same color as your theme background color, you can try change that to change the background color.

**Comment by lars-vc** [comment]
![image](https://user-images.githubusercontent.com/57136208/184161409-659e92d8-6ce4-4937-9b4a-dfea9254e022.png)
Mmmmh that's really strange (I have set the group to CocFloating now)
The weird text background still remains (I have tried rebooting the entire machine)

**Comment by ziontee113** [comment]
Hi @lars-vc now you can change it with the option `["text_highlight_group"] = "your_highlight_group"`

**Comment by lars-vc** [comment]
Wonderful, it works! :tada: 
Thanks for the quick updates :smile:
