### ISSUE TITLE
[Feature request] transparency with hex codes

### ISSUE THREAD

**Issue by lars-vc** [ziontee113/color-picker.nvim#16]
Currently, transparency doesn't work with hex codes, relevant part of README:
> Transparency Mode
 Press t to toggle Transparency Slider. While this mode is active, you will only be able to output the color as rgba() or hsla(). If you want to output as HEX, press t to get out of Transparency Mode, and you'll be able to press o to output your color as HEX.

Could it be possible for this to also work with hex? (because exiting transparency mode of course loses the transparency info)
It's pretty standard for the transparency value to be at the back of the hexcode, going from 00 to FF. (I know there are outliers, but I would rather have a way to add transparency then no way at all).

**Comment by lars-vc** [comment]
I think I could attempt to make this and pr this, if you would like.

**Comment by ziontee113** [comment]
Thank you @lars-vc for opening the issue. When making the plugin I didn't know that people use HEX for transparency :smile: 
It'd be great if you can make a PR. I'm quite budy at the moment so I unfortunately can't add this feature any time soon, but I'm planning to in the future.

**Comment by lars-vc** [comment]
Mmh how do I go about testing out what I wrote (I use vimplug, so do I just need to put what I wrote into my autoload directory?) or is there an easier way?

**Comment by ziontee113** [comment]
You can do something like:

```lua
vim.cmd([[set runtimepath+=~/some_where_on_computer/color-picker.nvim/]])
require("color-picker")
```
