### ISSUE TITLE
[Bug] Pressing ctrl+c while in the menu opens another one

### ISSUE THREAD

**Issue by lars-vc** [ziontee113/color-picker.nvim#18]
![image](https://user-images.githubusercontent.com/57136208/184843892-88edfea9-c861-49e2-9bfe-6d2ea37f2cf8.png)
:smiley:
Ill try and resolve this in my pr as well (if you don't mind)

**Comment by ziontee113** [comment]
>Ill try and resolve this in my pr as well (if you don't mind)

Yeah go ahead man :smile:

**Comment by lars-vc** [comment]
![image](https://user-images.githubusercontent.com/57136208/184856862-baf26174-5906-41b4-b9e5-fb2272b1d8c9.png)
It's bit of a hacky solution because I am not familiar with the nvim api, but it works

**Comment by ziontee113** [comment]
Hmm... I don't think it's necessary to use autocmds in this case. We just need to map `C-c` in our plugin to do `:q` for example. Don't worry about it, I'll do it in a few hours.
