### ISSUE TITLE
Displaying automatically colors in files

### ISSUE THREAD

**Issue by roland-rollo** [ziontee113/color-picker.nvim#3]
Hi,

I was wondering if I can replace `colorizer.lua` with using only your's `color-picker.nvim`. If I open some files and there are, like hex numbers meaning come colors it would show, what color it's. I mean something like this:
![ps_20220629004516](https://user-images.githubusercontent.com/44477799/176316978-906b133f-8186-4a10-aa9d-d315943e788d.png)

**Comment by ziontee113** [comment]
I think you should stick to `colorizer.lua` for now, until better alternatives show up. I use colorizer too.

**Comment by ziontee113** [comment]
Thanks man. Take care :)
