### ISSUE TITLE
Not an editor command: PickColor

### ISSUE THREAD

**Issue by timoleistner** [ziontee113/color-picker.nvim#4]
I've installed the plugin with 
```
use "ziontee113/color-picker.nvim"
```
and packer shows the plugin as installed in `:PackerStatus` but if I try to run the command, `:PickColor` as well as `PickColorInsert` both return the error with the corresponding command (`E492: Not an editor command: PickColor`).
Setting the keymaps didnt help either.

**Comment by ziontee113** [comment]
Oh.... That's my bad. Using this will solve the issue:

Option 1:
```lua
require("color-picker")
```

Option 2:
```lua
require("color-picker").setup({
	["icons"] = { "ﱢ", "" }, -- pick icons you want
	["keymap"] = { -- map keys as you want
		["U"] = "<Plug>Slider5Decrease",
		["O"] = "<Plug>Slider5Increase",
	},
})
```

**Comment by timoleistner** [comment]
Alright this works :)
Consider adding this as an installation instruction
```
use ({"ziontee113/color-picker.nvim",
    config = function()
        require("color-picker")
    end,
})
```

**Comment by ziontee113** [comment]
Thank you for the suggestion, will do :)
