### ISSUE TITLE
Feature Request: Command for chaning color space

### ISSUE THREAD

**Issue by timoleistner** [ziontee113/color-picker.nvim#5]
A nice and simple to implement feature should be to change the color space of the color under the cursor to another.
The functions are already there
https://github.com/ziontee113/color-picker.nvim/blob/355d6d56610e0f674741eaa31cabe0d7fbda5f33/lua/color-picker/utils/init.lua#L3
https://github.com/ziontee113/color-picker.nvim/blob/355d6d56610e0f674741eaa31cabe0d7fbda5f33/lua/color-picker/utils/init.lua#L8
After picking up the current colors under the cursor, they could be used and the output would replace the current color with the other color space (without the in between step of manually changing color).

**Comment by ziontee113** [comment]
So you mean like a Command to Convert colors from RGB to Hex and vice versa?

**Comment by timoleistner** [comment]
Exactly.

**Comment by 4strodev** [comment]
Do you mean that you could do that without activating the color picker? Only with a key map? Because you can activate the color picker and select the output of your color and the plugin change automatically to color space.

**Comment by timoleistner** [comment]
Thats what I meant. Like I said "without the in between step of manually changing color").

**Comment by ziontee113** [comment]
Yeah you're gonna have to turn up the picker, then press `o` then `enter` for now. I'll implement this is 2-3 days.

**Comment by ziontee113** [comment]
Hi @timoleistner you can now use `ConvertHEXandRGB` and `ConvertHEXandHSL` commands to convert those color spaces from and to HEX color space.
