### ISSUE TITLE
Incorrect hsla -> rgba conversion 

### ISSUE THREAD

**Issue by mattiasbonte** [ziontee113/color-picker.nvim#8]
Hello, I've been testing your plugin today. Nice work :).

1: Conversion issue.
- Going from hsla -> rgba removes the percentage value and color values as well.
So when pressing `o` inside the picker for a `hsla` value, it converts it to a `rgba` value like shown in the code block below.
```
hsla(100, 10%, 10%, 0.1) -> o -> rgba(25, 28, 23)
```
But if I then activate the picker again, it shows me `hsla(15, 15%, 1%, 1)` which lost the 0.1% and became 100%.  If I convert it even further it loses all values and becomes a `rgb(0,0,0)` color.
![colorpicker](https://user-images.githubusercontent.com/65280774/176382102-4b421512-65a3-4d29-8570-894abcff0a54.gif)
I'm not such a css guru, so I don't know if this is correct behavior? If it is, please disregard my message.

2: I'm not really sure if this is intended, so also disregard if it was.
- I don't physically see the color transparency change when the transparency value is changed on rgba/hsla colors.

3: Just an idea..
- It would be nice to be able to convert a regular color to a hsla/rgba color as well from within the picker. Not sure if this is already possible?

Thank you.

**Comment by ziontee113** [comment]
Hello @mattiasbonte , thanks for opening the issue.
1. Converting from `hsla` to `rgba` with `o` deletes transparency value is a bug, I'll try to fix it. For now please use `r` for that instead.
2. You can't really program transparency in terminals, so I did not implement that.
3. Converting a color from / to `hsla/rgba` you can press `t` to toggle transparency mode.

**Comment by ziontee113** [comment]
Hi @mattiasbonte the 1. should be fixed now. Please update your plugin :)

**Comment by ziontee113** [comment]
Cheers mate. Take care :)
